name = "SDFReader"
uuid = "bd0b56a1-724b-4db5-9cfb-6781c02e0e49"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com>"]
version = "0.1.0"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
GeometryTypes = "0.7"
PyCall = "1.91"
Unitful = "0.18"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
